### ISSUE TITLE
Issues with installing smoke in Ubuntu

### ISSUE THREAD

**Issue by ghost** [skadistats/smoke#1]
Hi,
Thank you for the great work. But I encountered some problems installing smoke on my Linux machine. Following is my error message:
## Error compiling Cython file:

...
from libc.stdint cimport int64_t, uint64_t, uint32_t
from cpython cimport array

---

smoke/io/stream/generic.pxd:2:21: Name 'array' not declared in module 'cpython'

Traceback (most recent call last):
  File "setup.py", line 87, in <module>
    "smoke/replay/ticker.pyx"
  File "/usr/lib/pymodules/python2.7/Cython/Build/Dependencies.py", line 517, in cythonize
    cythonize_one(pyx_file, c_file, quiet, options)
  File "/usr/lib/pymodules/python2.7/Cython/Build/Dependencies.py", line 540, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: smoke/io/stream/entity.pyx

I think I did install Cython library. Any suggestions?

**Comment by ghost** [comment]
nvm, turned out that I didn't upgrade my cython lib. Thanks anyway
