### ISSUE TITLE
Doesn't build with Cython 0.22

### ISSUE THREAD

**Issue by qiemem** [skadistats/smoke#15]
Fails with

```
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 87, in <module>
    "smoke/replay/ticker.pyx"
  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 754, in cythonize
    aliases=aliases)
  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 649, in create_extension_list
    for file in nonempty(extended_iglob(filepattern), "'%s' doesn't match any files" % filepattern):
  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 103, in nonempty
    raise ValueError(error_msg)
ValueError: 'smoke/io/const.pyx' doesn't match any files
```

Seen on both OS X Mavericks and Yosemite, though I guess it's probably a change in Cython's dependency handling.

I _think_ I got around it by renaming `smoke/io/const.py` to `smoke/io/const.pyx` and commenting out line 59 in `setup.py` (that's `"smoke/replay/decoder/recv_prop/factory.pyx",`), but haven't been able to test much yet. I'll probably just downgrade cython to be sure.

**Comment by victorgan** [comment]
Same issue in Ubuntu 14.04.

**Comment by Noxville** [comment]
Removing the files that setup.py breaks on can work, but might have bad side effects.

**Comment by lukerobert** [comment]
I'm having the same issue. Is qiemem's solution the best way to get around this for now?

**Comment by yuankaiz** [comment]
same problem here in Ubuntu 14.04. 
Anyone has any ideas?
I followed @victorgan 's way, seemed working for now.

**Comment by lukerobert** [comment]
the solution that ended up working for me was downgrading cython. It was a couple months ago now but iirc that made it work without editing any of the smoke files.

**Comment by yuankaiz** [comment]
@lukerobert So which cython version did you downgraded to?

**Comment by lukerobert** [comment]
I downgraded to 0.21

**Comment by EvO-E** [comment]
Yep downgrading to cython 0.21 solves it.
