### ISSUE TITLE
const.pyx

### ISSUE THREAD

**Issue by kaanaksit** [skadistats/smoke#19]
smoke$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 87, in <module>
    "smoke/replay/ticker.pyx"
  File "/home/kaan/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 796, in cythonize
    aliases=aliases)
  File "/home/kaan/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 688, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/home/kaan/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 107, in nonempty
    raise ValueError(error_msg)
ValueError: 'smoke/io/const.pyx' doesn't match any files

**Comment by misfim** [comment]
Have the same issue. Fedora 25, Cython==0.25

**Comment by spheenik** [comment]
Smoke is pretty much abandoned. I suppose you want to parse recent dota 2 (source 2 engine) replays anyway, which smoke cannot do (it supports only source 1). Good luck anyway!

**Comment by misfim** [comment]
Sad to hear it(( Anyway, thanks for quick answer.

В Среда, 25 янв. 2017 в 10:59 , Martin Schrodt 
<notifications@github.com> написал:

**Comment by spheenik** [comment]
You're welcome. Current parsers available are Clarity (Java, by me) and Manta (Go, from Dotabuff).
